soda_certification:
  target: prod
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: "SODA_CERTIFICATION"
      warehouse: "SODA_WH"
      schema: "STAGING"
      threads: 4
      client_session_keep_alive: False
      query_tag: "dbt_dev"
      quote_identifiers: false
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: "SODA_CERTIFICATION"
      warehouse: "SODA_WH"
      schema: "STAGING"
      threads: 4
      client_session_keep_alive: False
      query_tag: "dbt_prod"
      quote_identifiers: false
