services:
  superset-db:
    image: postgres:13
    container_name: superset-postgres
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    volumes:
      - superset-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "superset"]
      interval: 5s
      retries: 5
    restart: always

  superset-redis:
    image: redis:7-alpine
    container_name: superset-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  superset:
    image: apache/superset:latest-dev
    container_name: superset-app
    environment:
      - SUPERSET_SECRET_KEY=your-superset-secret-key-here
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - SUPERSET_WEBSERVER_PORT=8088
      - SUPERSET_WEBSERVER_ADDRESS=0.0.0.0
      - DATABASE_URL=postgresql://superset:superset@superset-db:5432/superset
      - REDIS_URL=redis://superset-redis:6379/0
    volumes:
      - superset-data:/app/superset_home
      - ./data:/app/soda_data
      - ./superset_config.py:/app/superset_config.py
    ports:
      - "8089:8088"
    command: >
      sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      superset-db:
        condition: service_healthy
      superset-redis:
        condition: service_healthy

volumes:
  superset-postgres-data:
  superset-data:
