# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "datashift-dev-tfstate-120430499886-eu-west-1"
    dynamodb_table = "datashift-dev-tf-locks"
    encrypt        = true
    key            = "network/vpc/terraform.tfstate"
    region         = "eu-west-1"
  }
}
