# Soda Configuration for STAGING Layer
# Database: SODA_CERTIFICATION, Schema: STAGING
# Purpose: Data quality monitoring for transformed data

data_source soda_certification_staging:
  type: snowflake
  connection:
    account: ${SNOWFLAKE_ACCOUNT}
    username: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    role: ${SNOWFLAKE_ROLE}
    warehouse: ${SNOWFLAKE_WAREHOUSE}
    database: ${SNOWFLAKE_DATABASE}
    schema: STAGING
    insecure_mode: True # To handle certificate validation issues
    # Performance optimizations for large dataset
    query_tag: 'soda_quality_check_staging'
    # Increase timeout for large queries
    network_timeout: 600
    # Use larger warehouse for better performance
    warehouse_size: 'MEDIUM'

# Soda Cloud Integration
soda_cloud:
  host: ${SODA_CLOUD_HOST}
  api_key_id: ${SODA_CLOUD_API_KEY_ID}
  api_key_secret: ${SODA_CLOUD_API_KEY_SECRET}

# Note: checks are defined in separate files under soda/checks/staging