name: Soda Scan (RAW)

on:
  push:
    branches:
      - main
    paths:
      - "soda/configuration/configuration_raw.yml"
      - "soda/checks/raw/**"
      - "dbt/**"
      - "airflow/**"
      - ".github/workflows/soda-raw.yml"
      - "**/*.sql"
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    paths:
      - "soda/configuration/configuration_raw.yml"
      - "soda/checks/raw/**"
      - "dbt/**"
      - "airflow/**"
      - ".github/workflows/soda-raw.yml"
      - "**/*.sql"
      - "**/*.yml"
      - "**/*.yaml"

concurrency:
  group: soda-raw-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  soda_scan_raw:
    name: Run Soda Scan on RAW
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional but helpful to print which config & checks will be used
      - name: List Soda files
        run: |
          echo "Configuration:"
          ls -la soda/configuration/configuration_raw.yml || true
          echo "Checks:"
          ls -la soda/checks/raw || true

      - name: Perform Soda Scan (RAW)
        id: soda
        uses: sodadata/soda-github-action@main
        env:
          # ---- Soda Cloud (store in GitHub Secrets) ----
          SODA_CLOUD_HOST: ${{ secrets.SODA_CLOUD_HOST }}
          SODA_CLOUD_API_KEY_ID: ${{ secrets.SODA_CLOUD_API_KEY_ID }}
          SODA_CLOUD_API_KEY_SECRET: ${{ secrets.SODA_CLOUD_API_KEY_SECRET }}

          # ---- Snowflake (store in GitHub Secrets) ----
          SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:      ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE:      ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE:  ${{ secrets.SNOWFLAKE_DATABASE }}

        with:
          # Pin the Soda Library version (adjust if you need a different one)
          soda_library_version: v1.0.4

          # Match the data source name defined in your configuration file:
          #   data_source soda_certification_raw:
          data_source: soda_certification_raw

          # Paths relative to repo root
          configuration: ./soda/configuration/configuration_raw.yml
          checks: ./soda/checks/raw

      # Upload Soda run artifacts for debugging/traceability
      - name: Upload Soda Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: soda-raw-artifacts
          path: |
            .soda/**/*
            soda/**/*
          if-no-files-found: ignore

      # Optionally, post a PR comment if checks fail (keeps the failure visible in PR)
      - name: Comment on PR when checks fail
        if: failure() && github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ❌ **Soda RAW checks failed.**
            Check the job logs and the uploaded artifacts (`soda-raw-artifacts`) for details.