name: Soda Data Quality Scan (mart)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: soda-scan-mart-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  soda_scan_mart:
    runs-on: ubuntu-latest
    name: Run Soda Scan (mart)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Soda Library Action (mart)
        id: soda_mart
        uses: sodadata/soda-github-action@v1.0.2
        continue-on-error: true
        env:
          # Soda Cloud
          SODA_CLOUD_API_KEY_ID: ${{ secrets.SODA_CLOUD_API_KEY_ID }}
          SODA_CLOUD_API_KEY_SECRET: ${{ secrets.SODA_CLOUD_API_KEY_SECRET }}
          SODA_CLOUD_HOST: ${{ secrets.SODA_CLOUD_HOST }}
          # Snowflake (match placeholders in your config)
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        with:
          soda_library_version: v1.0.4
          data_source: soda_certification_mart
          configuration: soda/configuration/configuration_mart.yml
          checks: soda/checks/mart/*.yml

      - name: Persist Soda results
        if: always()
        shell: bash
        run: |
          printf '%s\n' "${SCAN_RESULTS:-[]}" > soda_scan_results_mart.json
          printf '%s\n' "${SCAN_CLOUD_LINK:-}" > soda_scan_results_mart.link.txt

      - name: Decide job outcome (fail only on execution errors)
        if: always()
        shell: bash
        run: |
          code="${SCAN_EXIT_CODE:-}"
          echo "SCAN_EXIT_CODE=${code}"
          echo "SCAN_CLOUD_LINK=${SCAN_CLOUD_LINK:-}"
          echo "SCAN_RESULTS=${SCAN_RESULTS:-}"
          if [[ -z "$code" ]]; then
            echo "Missing SCAN_EXIT_CODE → execution/config error."
            exit 1
          fi
          if [[ "$code" -eq 1 ]]; then
            echo "Soda execution error (config/connectivity/runtime)."
            exit 1
          fi
          echo "Checks executed (exit ${code}). Keeping the workflow green."
          exit 0

      - name: Upload scan results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: soda-scan-results-mart
          path: |
            soda_scan_results_mart.json
            soda_scan_results_mart.link.txt
          if-no-files-found: ignore

      - name: Comment on PR with link + summary
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@8c77f42bbcc27c832a3a5962c8f9a60e34b594f3
        continue-on-error: true
        with:
          message: |
            **Soda scan (mart) completed**
            **Soda Cloud:** ${SCAN_CLOUD_LINK}

            **Summary (Pass/Warn/Fail counts):**
            ```
            ${SCAN_RESULTS}
            ```

            _Artifacts_: **soda-scan-results-mart** (JSON + link)
        env:
          SCAN_CLOUD_LINK: ${{ env.SCAN_CLOUD_LINK }}
          SCAN_RESULTS: ${{ env.SCAN_RESULTS }}