name: Scan for data quality

on: push

jobs:
  soda_scan:
    runs-on: ubuntu-latest
    name: Run Soda Scan (raw)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Soda Library Action
        uses: sodadata/soda-github-action@v1.0.2
        env:
          SODA_CLOUD_API_KEY: ${{ secrets.SODA_CLOUD_API_KEY_ID }}
          SODA_CLOUD_API_SECRET: ${{ secrets.SODA_CLOUD_API_KEY_SECRET }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        with:
          soda_library_version: v1.0.4
          data_source: soda_certification_raw
          configuration: soda/configuration/configuration_raw.yml
          checks: soda/checks/raw/*.yml