name: Scan for data quality (raw)

on: push

jobs:
  soda_scan:
    runs-on: ubuntu-latest
    name: Run Soda Scan (raw)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Soda Library Action
        uses: sodadata/soda-github-action@v1.0.2
        env:
          # --- Soda Cloud (match placeholders in config) ---
          SODA_CLOUD_API_KEY_ID: ${{ secrets.SODA_CLOUD_API_KEY_ID }}
          SODA_CLOUD_API_KEY_SECRET: ${{ secrets.SODA_CLOUD_API_KEY_SECRET }}
          SODA_CLOUD_HOST: ${{ secrets.SODA_CLOUD_HOST }}   # e.g. https://cloud.soda.io

          # --- Snowflake (match placeholders in config) ---
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}     # e.g. xy12345.eu-west-1
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}           # NOT SNOWFLAKE_USERNAME
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}

        with:
          soda_library_version: v1.0.4
          data_source: soda_certification_raw
          configuration: soda/configuration/configuration_raw.yml
          checks: soda/checks/raw/*.yml